### PR TITLE
Downgrade Bootstrap to alpha2 which is the version we started with

### PR DESCRIPTION
**Pull request by blhough**
Downgrade Bootstrap to alpha2 which is the version we started with.

### CODE REVIEW

**Comment by LinnierGames** [comment]
:DDDDDDDDDDDD

**Comment by blhough** [comment]
DONT MESS WITH THE VERSIONS
(unless good reason)

**Comment by LinnierGames** [comment]
Ahhhh, I had a feeling that the '^' symbol was causing the updating past alpha 2

**Comment by blhough** [comment]
This fix should be added to a branch that doesn't have other side effects

**Pull request closed without merging**
